programs:
  dummy-program:
    cmd: ["echo", "Hello from dummy!"]
    numprocs: 2
    autostart: true
    autorestart: unexpected
    exitcodes: [0]
    startretries: 3
    starttime: 5
    stopsignal: TERM
    stoptime: 10
    stdout: /tmp/dummy.stdout
    stderr: /tmp/dummy.stderr
    env: {}
    workingdir: /tmp

  server:
    cmd: ["SERVER_SH_PATH"]
    numprocs: 1
    umask: 022
    workingdir: WORKDIR
    autostart: true
    autorestart: unexpected
    exitcodes:
      - 0
      - 2
    startretries: 3
    starttime: 2
    stopsignal: TERM
    stoptime: 10
    stdout: /tmp/nginx.stdout
    stderr: /tmp/nginx.stderr
    env:
      SHOW_NAME: server-demo
      STARTED_BY: taskmaster
      ANSWER: "42"

  crasher:
    cmd: ["CRASHER_PATH", "1"]
    numprocs: 1
    autostart: false
    autorestart: unexpected
    exitcodes: [0]
    startretries: 3
    starttime: 1
    stopsignal: TERM
    stoptime: 2
    stdout: /tmp/crasher.stdout
    stderr: /tmp/crasher.stderr
    env: {}
    workingdir: WORKDIR

  longrunner:
    cmd: ["LONGRUNNER_PATH"]
    numprocs: 1
    autostart: true
    autorestart: always
    exitcodes: [0]
    startretries: 3
    starttime: 1
    stopsignal: TERM
    stoptime: 5
    stdout: /tmp/longrunner.stdout
    stderr: /tmp/longrunner.stderr
    env: {}
    workingdir: WORKDIR

  slowstopper:
    cmd: ["SLOWSTOPPER_PATH"]
    numprocs: 1
    autostart: true
    autorestart: never
    exitcodes: [0]
    startretries: 1
    starttime: 1
    stopsignal: USR1
    stoptime: 3
    stdout: /tmp/slowstopper.stdout
    stderr: /tmp/slowstopper.stderr
    env: {}
    workingdir: WORKDIR

  envreporter:
    cmd: ["ENVREPORTER_PATH"]
    numprocs: 1
    umask: 0o077
    workingdir: /tmp
    autostart: true
    autorestart: never
    exitcodes: [0]
    startretries: 1
    starttime: 0
    stopsignal: TERM
    stoptime: 2
    stdout: /tmp/envreporter.out
    stderr: /tmp/envreporter.err
    env:
      TM_FOO: hello
      TM_BAR: "42"
      TM_GREETING: "salut depuis taskmaster"